# CI - Selenium + Mocha + Mochawesome
on:
  push:
    branches: [Action]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Run Mocha tests
      - name: Run Mocha tests
        run: npm run tc01_login
    